spring:
  application:
    name: pub
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/clinic?currentSchema=public
    username: postgres
    password: zhang123
server:
  port: 0
mybatis-plus:
  type-aliases-package: com.example.pub.entity
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
