spring:
  application:
    name: pub
  profiles:
    active: dev
server:
  port: 0
mybatis-plus:
  type-aliases-package: com.example.pub.entity
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl